### ISSUE TITLE
Fail to use the repo in my project.

### ISSUE THREAD

**Issue by xuht724** [erigontech/interfaces#226]
I am new in graph, so the problem may be stupid.

I am trying to use this repo to send grpc with a local Erigon node.

First I git clone to my project and use protoc to compile it:

```
git clone https://github.com/erigontech/interfaces.git
```

And then I use protoc to compile it 
```
protoc \
  --proto_path=./interfaces \
  --go_out=./interfaces \
  --go-grpc_out=./interfaces \
  ./interfaces/remote/ethbackend.proto
```

I use replace in the go.mod.
```
module github.com/xuht724/erigon_grpc

go 1.22.3

require (
	github.com/erigontech/interfaces v0.0.0-20240802131416-fd1e1f60b2d7 // indirect
	golang.org/x/net v0.25.0 // indirect
	golang.org/x/sys v0.20.0 // indirect
	golang.org/x/text v0.15.0 // indirect
	google.golang.org/genproto/googleapis/rpc v0.0.0-20240528184218-531527333157 // indirect
	google.golang.org/grpc v1.65.0 // indirect
	google.golang.org/protobuf v1.34.2 // indirect
)
replace github.com/erigontech/interfaces => ./interfaces
```

I get two files `ethbackend_grpc.pb.go` and `ethbackend.pb.go` in the `myprojects/interfaces/remote`

However, when I try to use `go run main.go` to use the interfaces/remote/ethbackend.pb.go, there is an error:
```
interfaces/remote/ethbackend.pb.go:10:2: "./types" is relative, but relative import paths are not supported in module mode
interfaces/remote/ethbackend.pb.go:11:2: missing go.sum entry for module providing package github.com/golang/protobuf/ptypes/empty (imported by github.com/erigontech/interfaces/remote); to add:
        go get github.com/erigontech/interfaces/remote@v0.0.0-20240802131416-fd1e1f60b2d7
main.go:7:2: found packages remoteproto (ethbackend.pb.go) and remote (keep.go) in /home/os/haotian/erigon_grpc/interfaces/remote
```

I would like to ask how to use this repo in my go project.

**Comment by AskAlexSharov** [comment]
Erigon is Go project: 
- here https://github.com/erigontech/erigon/blob/959bc3752f107119f3acf499e68e47d0733082e9/erigon-lib/tools.go#L21

- here https://github.com/erigontech/erigon/blob/959bc3752f107119f3acf499e68e47d0733082e9/erigon-lib/Makefile#L63

- and https://github.com/erigontech/interfaces/blob/fd1e1f60b2d7799b21a33550f2eb73891b4cac87/remote/kv.proto#L45

**Comment by xuht724** [comment]
> Erigon is Go project:
> 
> * here https://github.com/erigontech/erigon/blob/959bc3752f107119f3acf499e68e47d0733082e9/erigon-lib/tools.go#L21
> * here https://github.com/erigontech/erigon/blob/959bc3752f107119f3acf499e68e47d0733082e9/erigon-lib/Makefile#L63
> * and https://github.com/erigontech/interfaces/blob/fd1e1f60b2d7799b21a33550f2eb73891b4cac87/remote/kv.proto#L45

I meet a puzzling mistake, currently I use below script to run Erigon and RPCDaemon:
```sh
nohup xxx/erigon \
    --datadir="xxx" \
    --chain=mainnet \
    --private.api.addr=localhost:9090\
    --http.port=8545 \
    --http \
    --authrpc.addr localhost \
    --authrpc.port 8552 \
    --authrpc.vhosts localhost \
    --authrpc.jwtsecret /home/os/ethereum/jwt.hex\
    --port=30304\
    --http.api=eth,debug,net,trace,web3,erigon \
    --ws \
```

```sh
nohup xxx/rpcdaemon \
     --private.api.addr=localhost:9090 \
     --grpc \
     --datadir="/home/os/ethereum/erigon/data" \
```

The rpcdaemon log shows that the grpc service has run:
```
JsonRpc endpoint opened                  ws=false ws.compression=false grpc=true http.url=127.0.0.1:8545 grpc.port=8547
```
However when I use below go code to retrieve block info, I meet the problem:
```go
package main

import (
	"context"
	"log"

	pb "github.com/ledgerwatch/erigon-lib/gointerfaces/remote"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

func main() {
	conn, err := grpc.NewClient("localhost:8547", grpc.WithTransportCredentials(insecure.NewCredentials()))

	if err != nil {
		log.Fatalf("did not connect: %v", err)
	}
	defer conn.Close()

	client := pb.NewETHBACKENDClient(conn)
	req := &pb.BlockRequest{
		BlockHeight: 20524697,
	}

	log.Println(req)

	res, err := client.Block(context.Background(), req)
	if err != nil {
		log.Fatalf("could not get block: %v", err)
	}

	log.Printf("Block response: %v", res)
}
```
The result is:
```
2024/08/15 01:57:04 block_height:20524697
2024/08/15 01:57:04 could not get block: rpc error: code = Unimplemented desc = unknown service remote.ETHBACKEND
exit status 1
```

If there is any error in the process of starting Erigon and rpcdaemon and grpc service.

**Comment by AskAlexSharov** [comment]
GRPC: --private.api.addr=localhost:9090 
You using worng port: grpc.NewClient("localhost:8547"

**Comment by xuht724** [comment]
> GRPC: --private.api.addr=localhost:9090 You using worng port: grpc.NewClient("localhost:8547"

I got the same error using 9090 port:
```
2024/08/15 10:09:37 block_height:20524697
2024/08/15 10:09:37 could not get block: rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference
exit status 1
```

I notice that the rpcdaemon's gprc port is 8547, is there any difference between this grpc port with 9090 port

**Comment by AskAlexSharov** [comment]
JsonRPC and AuthRPC (also JsonRPC) and GRPC - are 3 different ports

`nil pointer dereference` - means error is in logs

**Comment by AskAlexSharov** [comment]
about ports: https://github.com/erigontech/erigon?tab=readme-ov-file#default-ports-and-firewalls

**Comment by xuht724** [comment]
> JsonRPC and AuthRPC (also JsonRPC) and GRPC - are 3 different ports
> 
> `nil pointer dereference` - means error is in logs

I do not find 'nil pointer dereference' in my debug logs. I would like ask if there is any error in using erigon-lib in my go code above.

**Comment by xuht724** [comment]
> JsonRPC and AuthRPC (also JsonRPC) and GRPC - are 3 different ports
> 
> `nil pointer dereference` - means error is in logs

I successfully using `NewKVClient` to get blockChangSet, but can not get data using `NewETHBACKENDClient`. That's really weird.

Thanks a lot for your timely and accurate answers.
